/**
 * Scans public/projects/<slug>/source/ for every project and (re)generates
 * src/generated/projects.ts, the static list Root.tsx maps over to render
 * one Composition per project under the "Projects" folder in Studio.
 * Must stay a plain data file (no fs) since Root.tsx is bundled for the
 * browser - see the calculate-metadata.md gotcha in remotion-best-practices.
 */
import {writeFileSync, readdirSync, existsSync} from "fs";
import path from "path";

const VIDEO_EXTENSION_RE = /\.(mp4|mov|webm)$/i;

const slugToPascalCase = (slug: string): string => {
  const parts = slug
    .split(/[_-]+/)
    .filter((part) => part.length > 0 && !/^\d+$/.test(part))
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1));
  return parts.length > 0 ? parts.join("") : `Project${slug.replace(/[^a-zA-Z0-9]/g, "")}`;
};

export interface ProjectEntry {
  slug: string;
  compositionId: string;
  mainSrc: string;
}

export const syncProjectsRegistry = (): ProjectEntry[] => {
  const projectsRoot = path.join("public", "projects");
  const slugs = existsSync(projectsRoot)
    ? readdirSync(projectsRoot, {withFileTypes: true})
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
    : [];

  const usedIds = new Set<string>();
  const entries: ProjectEntry[] = [];

  for (const slug of slugs) {
    const sourceDir = path.join(projectsRoot, slug, "source");
    const files = existsSync(sourceDir) ? readdirSync(sourceDir) : [];
    const videoFile = files.find((f) => VIDEO_EXTENSION_RE.test(f));
    if (!videoFile) {
      console.warn(`Skipping "${slug}": no video file in ${sourceDir}`);
      continue;
    }
    let compositionId = slugToPascalCase(slug);
    while (usedIds.has(compositionId)) compositionId += "2"; // rare collision guard
    usedIds.add(compositionId);
    entries.push({slug, compositionId, mainSrc: `projects/${slug}/source/${videoFile}`});
  }

  const outPath = path.join("src", "generated", "projects.ts");
  const body = `// AUTO-GENERATED by scripts/lib/projectsRegistry.ts - do not edit by hand.
// Regenerate: npx tsx scripts/new-project.ts <video>  (or npx tsx scripts/sync-projects.ts)

export interface ProjectEntry {
  slug: string;
  compositionId: string;
  mainSrc: string;
}

export const PROJECTS: ProjectEntry[] = ${JSON.stringify(entries, null, 2)};
`;
  writeFileSync(outPath, body);
  console.log(`Registry updated: ${outPath} (${entries.length} project${entries.length === 1 ? "" : "s"})`);

  return entries;
};
